From maven:3.9.11-eclipse-temurin-21 As build
COPY . .
WORKDIR /app
RUN mvn clean package -DskipTests

From eclipse-temurin:21-jdk-alpine
copy --from=build /target/glow-services-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT [ "java", "-jar", "app.jar" ]