
INSERT INTO products (
    name, slug, description, category, sub_category, brand, price, original_price, 
    stock_quantity, size, color, ingredients, how_to_use, rating, review_count, 
    featured, popular, new_arrival, on_sale, active, sort_order, created_at, updated_at
) VALUES

('Vitamin C Brightening Serum', 'vitamin-c-brightening-serum', 
'Powerful antioxidant serum that brightens skin, reduces dark spots, and promotes collagen production for a radiant, youthful complexion.', 
'skincare', 'serum', 'Glow Essentials', 899.00, 1299.00, 45, '30ml', NULL,
'Vitamin C (L-Ascorbic Acid), Hyaluronic Acid, Vitamin E, Ferulic Acid, Aloe Vera Extract',
'Apply 2-3 drops to clean skin in the morning. Follow with moisturizer and sunscreen.',
4.7, 156, true, true, false, true, true, 1, NOW(), NOW()),

('Hyaluronic Acid Moisturizing Cream', 'hyaluronic-acid-moisturizing-cream',
'Deep hydrating cream with triple molecular weight hyaluronic acid that plumps skin and provides 24-hour moisture.',
'skincare', 'moisturizer', 'AquaGlow', 1299.00, 1599.00, 32, '50ml', NULL,
'Hyaluronic Acid, Ceramides, Niacinamide, Shea Butter, Glycerin',
'Apply morning and evening to clean face and neck. Massage gently until absorbed.',
4.8, 234, true, true, false, true, true, 2, NOW(), NOW()),

('Gentle Foaming Cleanser', 'gentle-foaming-cleanser',
'pH-balanced foaming cleanser that removes impurities without stripping natural oils. Perfect for daily use.',
'skincare', 'cleanser', 'PureClean', 649.00, 799.00, 67, '150ml', NULL,
'Coconut-derived Surfactants, Chamomile Extract, Aloe Vera, Glycerin',
'Massage onto damp face, rinse thoroughly with lukewarm water. Use morning and evening.',
4.5, 89, false, true, false, true, true, 3, NOW(), NOW()),

('Retinol Anti-Aging Night Cream', 'retinol-anti-aging-night-cream',
'Advanced retinol formula that reduces fine lines, improves skin texture, and promotes cell renewal overnight.',
'skincare', 'night-cream', 'Age Defiance', 2199.00, 2799.00, 28, '30ml', NULL,
'Retinol 0.5%, Peptides, Squalane, Vitamin E, Jojoba Oil',
'Apply at night to clean skin. Start 2-3 times per week. Always use sunscreen during the day.',
4.6, 167, true, false, false, true, true, 4, NOW(), NOW()),

('Niacinamide Pore Refining Toner', 'niacinamide-pore-refining-toner',
'Alcohol-free toner with 10% niacinamide that minimizes pores, controls oil, and balances skin tone.',
'skincare', 'toner', 'ClearSkin Pro', 799.00, 999.00, 54, '200ml', NULL,
'Niacinamide 10%, Zinc PCA, Witch Hazel, Rose Water, Hyaluronic Acid',
'Apply with cotton pad or pat into skin with hands after cleansing, before serums.',
4.4, 98, false, true, true, false, true, 5, NOW(), NOW()),

('Full Coverage Foundation', 'full-coverage-foundation',
'Long-wearing, full coverage foundation with SPF 30 that provides flawless finish for up to 16 hours.',
'makeup', 'foundation', 'Glam Base', 1899.00, 2299.00, 38, '30ml', 'Medium Beige',
'Titanium Dioxide, Zinc Oxide, Hyaluronic Acid, Vitamin E',
'Apply with damp beauty sponge or foundation brush. Blend outward from center of face.',
4.7, 203, true, true, false, true, true, 6, NOW(), NOW()),

('Matte Lipstick Collection', 'matte-lipstick-collection',
'Highly pigmented matte lipstick that delivers bold color with comfortable, non-drying formula.',
'makeup', 'lipstick', 'Kiss Perfect', 899.00, 1199.00, 72, '4g', 'Ruby Red',
'Vitamin E, Jojoba Oil, Carnauba Wax, Iron Oxides',
'Apply directly to lips or use lip liner first for precise application.',
4.8, 145, false, true, true, false, true, 7, NOW(), NOW()),

('Eyeshadow Palette - Nude Collection', 'eyeshadow-palette-nude-collection',
'12-shade eyeshadow palette featuring warm nude tones with matte and shimmer finishes.',
'makeup', 'eyeshadow', 'Eye Artistry', 2499.00, 2999.00, 25, '48g', 'Nude Tones',
'Mica, Talc, Coconut Oil, Vitamin E, Iron Oxides',
'Apply with eyeshadow brush. Build color gradually. Use shimmer shades on lid center.',
4.9, 187, true, true, false, true, true, 8, NOW(), NOW()),

('Waterproof Mascara', 'waterproof-mascara',
'Smudge-proof, waterproof mascara that lengthens and volumizes lashes for 12-hour wear.',
'makeup', 'mascara', 'Lash Perfect', 1299.00, 1599.00, 56, '10ml', 'Black',
'Beeswax, Carnauba Wax, Vitamin E, Panthenol',
'Apply from lash base to tips in zigzag motion. Layer for more volume.',
4.6, 134, false, true, false, true, true, 9, NOW(), NOW()),

('Highlighting Powder', 'highlighting-powder',
'Silky highlighting powder that adds natural glow and luminosity to high points of the face.',
'makeup', 'highlighter', 'Glow Goddess', 1699.00, 1999.00, 41, '8g', 'Champagne Gold',
'Mica, Silica, Vitamin E, Jojoba Oil',
'Apply to cheekbones, nose bridge, and cupids bow with highlighting brush.',
4.5, 76, false, false, true, true, true, 10, NOW(), NOW()),

('Argan Oil Nourishing Shampoo', 'argan-oil-nourishing-shampoo',
'Sulfate-free shampoo enriched with Moroccan Argan oil that cleanses and nourishes dry, damaged hair.',
'haircare', 'shampoo', 'Hair Luxe', 899.00, 1199.00, 63, '300ml', NULL,
'Argan Oil, Keratin, Biotin, Aloe Vera, Coconut Oil',
'Apply to wet hair, massage into scalp, rinse thoroughly. Follow with conditioner.',
4.7, 189, true, true, false, true, true, 11, NOW(), NOW()),

('Deep Conditioning Hair Mask', 'deep-conditioning-hair-mask',
'Intensive weekly treatment mask that repairs damaged hair and restores shine and softness.',
'haircare', 'hair-mask', 'Repair Pro', 1499.00, 1899.00, 34, '200ml', NULL,
'Shea Butter, Coconut Oil, Protein Complex, Vitamin E, Panthenol',
'Apply to damp hair, leave for 10-15 minutes, rinse thoroughly. Use weekly.',
4.8, 167, true, false, false, true, true, 12, NOW(), NOW()),

('Heat Protection Spray', 'heat-protection-spray',
'Lightweight spray that protects hair from heat damage up to 230°C while adding shine.',
'haircare', 'heat-protectant', 'Style Shield', 799.00, 999.00, 48, '150ml', NULL,
'Silicones, Panthenol, Vitamin E, UV Filters',
'Spray on damp hair before blow-drying or on dry hair before using hot tools.',
4.4, 98, false, true, true, false, true, 13, NOW(), NOW()),

('Anti-Frizz Hair Serum', 'anti-frizz-hair-serum',
'Silky serum that controls frizz, adds shine, and protects against humidity for smooth hair.',
'haircare', 'hair-serum', 'Smooth Finish', 1199.00, 1499.00, 39, '50ml', NULL,
'Argan Oil, Silk Proteins, Dimethicone, Vitamin E',
'Apply 1-2 pumps to damp or dry hair, focusing on mid-lengths and ends.',
4.6, 123, false, true, false, true, true, 14, NOW(), NOW()),

('Exfoliating Body Scrub', 'exfoliating-body-scrub',
'Luxurious sugar scrub with essential oils that gently exfoliates and moisturizes skin.',
'bath-body', 'body-scrub', 'Spa Essence', 1299.00, 1599.00, 52, '250ml', NULL,
'Sugar, Coconut Oil, Shea Butter, Lavender Oil, Vitamin E',
'Massage onto damp skin in circular motions, rinse with warm water. Use 2-3 times weekly.',
4.7, 145, true, true, false, true, true, 15, NOW(), NOW()),

('Moisturizing Body Lotion', 'moisturizing-body-lotion',
'Fast-absorbing body lotion with 24-hour hydration that leaves skin soft and silky.',
'bath-body', 'body-lotion', 'Silk Touch', 699.00, 899.00, 74, '400ml', NULL,
'Shea Butter, Glycerin, Aloe Vera, Coconut Oil, Vitamin E',
'Apply to clean skin daily, massaging until fully absorbed.',
4.5, 167, false, true, false, true, true, 16, NOW(), NOW()),

('Relaxing Bath Bombs', 'relaxing-bath-bombs',
'Set of 6 natural bath bombs with essential oils for a spa-like bathing experience.',
'bath-body', 'bath-bombs', 'Bliss Bath', 999.00, 1299.00, 28, '6 pieces', 'Assorted',
'Epsom Salt, Essential Oils, Shea Butter, Natural Colors',
'Drop one bomb in warm bath water, relax and enjoy the aromatherapy.',
4.8, 89, true, false, true, true, true, 17, NOW(), NOW()),

('Hand Cream Set', 'hand-cream-set',
'Trio of intensive hand creams with different scents for soft, protected hands.',
'bath-body', 'hand-cream', 'Hand Care Plus', 799.00, 999.00, 67, '3x30ml', 'Assorted',
'Shea Butter, Glycerin, Vitamin E, Natural Fragrances',
'Apply to hands as needed throughout the day, massage until absorbed.',
4.4, 134, false, false, true, true, true, 18, NOW(), NOW()),

('Floral Fantasy Eau de Parfum', 'floral-fantasy-eau-de-parfum',
'Elegant floral fragrance with notes of jasmine, rose, and white musk for a feminine scent.',
'fragrance', 'eau-de-parfum', 'Scent Story', 2499.00, 2999.00, 23, '50ml', NULL,
'Alcohol, Fragrance, Water, Natural Extracts',
'Spray on pulse points: wrists, neck, behind ears. Do not rub after application.',
4.9, 178, true, true, false, true, true, 19, NOW(), NOW()),

('Fresh Citrus Body Mist', 'fresh-citrus-body-mist',
'Light, refreshing body mist with energizing citrus notes perfect for daily wear.',
'fragrance', 'body-mist', 'Fresh Air', 899.00, 1199.00, 45, '150ml', NULL,
'Water, Alcohol, Citrus Extracts, Natural Fragrance',
'Spray all over body for instant freshness. Reapply as desired.',
4.3, 98, false, true, true, true, true, 20, NOW(), NOW()),

('Long-Lasting Gel Polish', 'long-lasting-gel-polish',
'Professional gel nail polish that lasts up to 2 weeks with chip-resistant formula.',
'nail-care', 'gel-polish', 'Nail Perfect', 599.00, 799.00, 89, '15ml', 'Classic Red',
'Resin, Photoinitiators, Pigments, Conditioning Agents',
'Apply base coat, 2 thin coats of color, and top coat. Cure under UV/LED lamp.',
4.6, 234, false, true, false, true, true, 21, NOW(), NOW()),

('Nail Care Treatment Set', 'nail-care-treatment-set',
'Complete nail care kit with cuticle oil, base coat, strengthener, and top coat.',
'nail-care', 'nail-treatment', 'Nail Therapy', 1499.00, 1899.00, 34, '4x12ml', NULL,
'Vitamin E, Biotin, Keratin, Jojoba Oil, Calcium',
'Use products as directed for stronger, healthier nails in 2 weeks.',
4.7, 156, true, false, true, true, true, 22, NOW(), NOW()),

('Professional Makeup Brush Set', 'professional-makeup-brush-set',
'12-piece professional makeup brush set with synthetic bristles and wooden handles.',
'tools', 'makeup-brushes', 'Pro Beauty', 2199.00, 2799.00, 18, '12 pieces', NULL,
'Synthetic Bristles, Wood Handles, Metal Ferrules',
'Clean brushes regularly with brush cleaner or gentle shampoo.',
4.8, 145, true, true, false, true, true, 23, NOW(), NOW()),

('Beauty Blender Set', 'beauty-blender-set',
'Set of 3 latex-free makeup sponges for flawless foundation and concealer application.',
'tools', 'makeup-sponge', 'Blend Master', 899.00, 1199.00, 56, '3 pieces', 'Pink',
'Non-latex Foam, Antimicrobial Treatment',
'Dampen sponge before use. Bounce to blend makeup. Clean after each use.',
4.5, 198, false, true, true, true, true, 24, NOW(), NOW()),


('Men''s Face Wash Gel', 'mens-face-wash-gel',
'Deep cleansing face wash designed for men''s skin that removes oil and impurities.',
'mens', 'face-wash', 'Gent Care', 799.00, 999.00, 43, '150ml', NULL,
'Salicylic Acid, Charcoal, Tea Tree Oil, Menthol',
'Apply to wet face, massage gently, rinse thoroughly. Use morning and evening.',
4.4, 123, false, true, false, true, true, 25, NOW(), NOW()),

('Beard Growth Oil', 'beard-growth-oil',
'Nourishing beard oil that promotes growth, softens hair, and moisturizes skin underneath.',
'mens', 'beard-oil', 'Beard Master', 1299.00, 1599.00, 29, '30ml', NULL,
'Argan Oil, Jojoba Oil, Vitamin E, Essential Oils',
'Apply 3-5 drops to beard and massage into skin. Use daily for best results.',
4.7, 167, true, true, false, true, true, 26, NOW(), NOW()),


('SPF 50 Sunscreen Lotion', 'spf-50-sunscreen-lotion',
'Broad spectrum SPF 50 sunscreen that provides superior protection against UVA and UVB rays.',
'sun-care', 'sunscreen', 'Sun Shield', 899.00, 1199.00, 67, '100ml', NULL,
'Zinc Oxide, Titanium Dioxide, Vitamin E, Aloe Vera',
'Apply 30 minutes before sun exposure. Reapply every 2 hours or after swimming.',
4.6, 189, true, true, true, true, true, 27, NOW(), NOW()),

('Anti-Aging Face Serum', 'anti-aging-face-serum',
'Advanced peptide serum that reduces wrinkles, firms skin, and improves elasticity.',
'specialty', 'anti-aging-serum', 'Age Reverse', 3499.00, 4199.00, 15, '30ml', NULL,
'Peptides, Retinol, Hyaluronic Acid, Growth Factors, Vitamin C',
'Apply 2-3 drops to clean face at night. Follow with moisturizer.',
4.9, 87, true, false, false, true, true, 28, NOW(), NOW()),

('Organic Rose Hip Seed Oil', 'organic-rose-hip-seed-oil',
'100% pure, cold-pressed organic rose hip seed oil for natural skin regeneration and hydration.',
'natural', 'face-oil', 'Pure Nature', 1699.00, 2199.00, 31, '30ml', NULL,
'100% Organic Rosa Canina Seed Oil, Vitamin E',
'Apply 2-3 drops to clean face in the evening. Can be mixed with moisturizer.',
4.8, 134, true, true, true, false, true, 29, NOW(), NOW()),

('Vegan Lip Balm Set', 'vegan-lip-balm-set',
'Set of 3 vegan, cruelty-free lip balms with natural flavors and moisturizing ingredients.',
'natural', 'lip-balm', 'Green Beauty', 699.00, 899.00, 78, '3x4g', 'Assorted',
'Organic Coconut Oil, Shea Butter, Beeswax Alternative, Natural Flavors',
'Apply to lips as needed for soft, hydrated lips.',
4.4, 156, false, false, true, true, true, 30, NOW(), NOW());